# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarMeets' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarMeets
	pod 'KeychainSwift', '~> 13.0'
	pod 'JWTDecode', '~> 2.2'

  target 'CarMeetsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarMeetsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
